import Head from 'next/head';
import Image from 'next/image';
import Banner from '../components/banner';
import styles from '../styles/Home.module.css';
//styles file is imported as an object containing the styled components

import Card from '../components/card';

import coffeeStores from '../data/coffee-stores.json';

export default function Home() {

  const handleOnBannerClick = () => {
    console.log('hello i am the banner button')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner 
          buttonText="View stores nearby" 
          handleOnClick={handleOnBannerClick}
        />
        <div className={styles.heroImage}>
          <Image 
            src="/static/hero-image.png" 
            alt='coffee image' 
            width={700} height={400} 
          />
        </div>
        <div className={styles.cardLayout}>
          {coffeeStores.map( (coffeeStore) => {
            return (
              <Card 
                key={coffeeStore.id}
                name={coffeeStore.name} 
                imgUrl={coffeeStore.imgUrl}
                href={`/coffee-store/${coffeeStore.id}`}
                className={styles.card}
              />
            );
          })}
        </div>
      </main>

    </div>
  )
}
